### PR TITLE
lit carousel

### PR DESCRIPTION
**Pull request by AaryanSingh0017**
plz accept the PR under Hacktoberfest accepted label.

### CODE REVIEW

**Comment by bpod** [comment]
Looks good. There were some changes to main, so please pull latest into your branch and then I'll go ahead and merge.

**Comment by AaryanSingh0017** [comment]
I have made the changes plz review it.

**Comment by bpod** [comment]
Ahh TypeScript! Excellent!

laughing-palpatine

**Comment by AaryanSingh0017** [comment]
Anything wrong ?

**Pull request merged**
